CREATE TABLE Categorias(
CodCategoria INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Descripcion VARCHAR(100)
);

CREATE TABLE Productos(
CodProducto INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Precio DECIMAL NOT NULL,
Cantidad INT NOT NULL,
Descripcion NVARCHAR(50) NOT NULL,
CodCategoria INT NOT NULL,
FOREIGN KEY (CodCategoria) references Categorias (CodCategoria) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Clientes(
CodCliente INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Telefono VARCHAR(9) NOT NULL,
Direccion VARCHAR(200) NOT NULL
);

CREATE TABLE Empleados(
CodEmpleado INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
Telefono VARCHAR(9) NOT NULL,
Cargo VARCHAR(20) NOT NULL,
Direccion VARCHAR(200) NOT NULL,
);

CREATE TABLE Ventas(
CodVenta INT IDENTITY PRIMARY KEY,
FechaHora DATETIME NOT NULL,
FormaPago VARCHAR(20) NOT NULL,
Estado VARCHAR(10) NOT NULL,
CodCliente INT NOT NULL,
CodEmpleado INT NOT NULL,
FOREIGN KEY (CodCliente) references Clientes (CodCliente) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (CodEmpleado) references Empleados (CodEmpleado) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DetalleVentas(
CodDetalleVenta INT IDENTITY PRIMARY KEY,
Cantidad INT NOT NULL,
SubTotal DECIMAL NOT NULL,
CodProducto INT NOT NULL,
CodVenta INT NOT NULL,
FOREIGN KEY (CodProducto) references Productos (CodProducto) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (CodVenta) references Ventas (CodVenta) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Roles(
CodRol INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Descripcion VARCHAR(100)
);

CREATE TABLE Usuarios(
CodUsuario INT IDENTITY PRIMARY KEY,
Correo VARCHAR(50) NOT NULL,
Contraseña VARCHAR(12) NOT NULL,
CodRol INT NOT NULL,
CodEmpleado INT NOT NULL,
FOREIGN KEY (CodRol) references Roles (CodRol) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (CodEmpleado) references Empleados (CodEmpleado) ON UPDATE CASCADE ON DELETE CASCADE
);

